### ISSUE TITLE
Investigate changed TLS behavior with 8 pre-release

### ISSUE THREAD

**Issue by redcatbear** [exasol/exasol-testcontainers#232]
## Situation

When trying to get the ETC working with Exasol 8 pre-release, there seems to be a subtle difference in TLS handling. We observed terminated connections where client errors were expected.

```[tasklist]
### Tasks
- [ ] Investigate TLS behavior with valid certificate
- [ ] Investigate TLS behavior with invalid certificate
- [ ] Adapt ETC to changes in error reporting
```
